### ISSUE TITLE
Contributing to project

### ISSUE THREAD

**Issue by yugely** [vasilakisfil/viska#31]
I'm looking to contribute to this project. I'm building out a VoIP as a personal project and am on board with the "whys" in the readme. I know the basics of SIP, I'm familiar with Rust. I'm unsure about how to go about starting up the server, or how to begin really. 
I forked the project. If you could give me a basic run down at your convenience, I would be greatly appreciative.
My email is trichtme@gmail.com

Also, any pointers to start out would be great as well.

**Comment by vasilakisfil** [comment]
Hi!

Thanks for reaching out! I think Viska is in a very wip state now and it will be a bit risky for you to contribute. Once I have settled down regarding the architecture (almost there!) then I think it will be much easier to contribute either on the core functionalities, or just on traits implementations, like Server, Transport, Transaction, Processors etc, so we can have a wide selection to choose from. Possibly these might need to live under a different repo.

A big part of Viska is [rsip](https://github.com/vasilakisfil/rsip), I guess you already know that in SIP tons of stuff depend on the actual headers :). rsip is a much safer crate to contribute, and it's a still tightly related to Voip. rsip is done pretty much regarding its own architecture, remaining things is to add support for more headers, especially typed headers. At the moment, I am working on a [branch](https://github.com/vasilakisfil/rsip/tree/feat/dns-resolver) there that implements [RFC 3263](https://datatracker.ietf.org/doc/html/rfc3263). Not sure if you have seen that RFC, but damn it's so complex if you wanna go all the way. Good news though I am almost done, need to write some more tests and re-organize the files/exports :) Probably it will be split to a separate crate though (now it's under a feature flag) as it adds a lot of code + deps and doesn't constitute as a simple feature anymore.

If you are not interested in contributing in rsip, I ll make sure to ping you in a couple a months from now (probably just after christmas) when the main Viska architecture will have implemented.

**Comment by yugely** [comment]
Wicked, I'm going to do some onboarding today. Thank you for the great reply!
